apiVersion: v1
kind: ConfigMap
metadata:
  name: worldbest-config
  namespace: worldbest
data:
  NODE_ENV: "production"
  API_URL: "https://api.worldbest.ai"
  WS_URL: "wss://api.worldbest.ai/ws"
  REDIS_URL: "redis://redis-service:6379"
  RABBITMQ_URL: "amqp://worldbest:worldbest123@rabbitmq-service:5672/worldbest"
  MINIO_ENDPOINT: "minio-service:9000"
  PINECONE_INDEX: "worldbest"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: worldbest
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
        worker_connections 4096;
        use epoll;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        client_max_body_size 100m;

        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css text/xml text/javascript 
                   application/json application/javascript application/xml+rss;

        include /etc/nginx/conf.d/*.conf;
    }